//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_details
    {
        public int detail_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public decimal subtotal { get; set; }
        public bool active { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual products products { get; set; }
    }
}
